export const siteTaskDefinitions = [
  {
  key: 'listing',
  label: 'Business Listing',
  route: '/listing',
  description: 'Curated business listing content.',
  contentType: 'listing',
  enabled: true,
},
  {
    key: 'classified',
    label: 'Classified',
    route: '/classified',
    description: 'Short-form posts for roles, rentals, equipment, and time-sensitive local offers.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Article',
    route: '/article',
    description: 'Guides, interviews, and checklists for buyers and operators who already narrowed their shortlist.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'image',
    label: 'Image',
    route: '/image',
    description: 'Portfolio and campaign imagery when the visual story matters as much as the written summary.',
    contentType: 'image',
    enabled: false,
  },
  {
    key: 'profile',
    label: 'Profile',
    route: '/profile',
    description: 'Identity pages for founders, practice leads, and brand accounts tied to your listings.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Social Bookmarking',
    route: '/sbm',
    description: 'Research shelves for links, tender references, and documents your team revisits often.',
    contentType: 'sbm',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Comment',
    route: '/blog',
    description: 'Threaded responses attached to articles for questions and follow-up discussion.',
    contentType: 'comment',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF',
    route: '/pdf',
    description: 'Downloadable menus, rate cards, policies, and technical PDFs next to your listings.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Organization',
    route: '/team',
    description: 'Company and collective pages when several listings roll up to one legal entity.',
    contentType: 'org',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
